resources:
  - k8s-manifests/api.yaml
  - k8s-manifests/db.yaml
  - k8s-manifests/web.yaml
configMapGenerator:
  - name: postgres-data
    files:
      - ./db/words.sql
generatorOptions:
  disableNameSuffixHash: true