apiVersion: v1
kind: Service
metadata:
  name: my-postgres-db
  labels:
    app: my-postgres-db
spec:
  selector:
    app: my-postgres-db
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP
